force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/PosterURL__c.field-meta.xml
<CustomField>
    <fullName>PosterURL__c</fullName>
    <label>Poster URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdbId__c.field-meta.xml
<CustomField>
    <fullName>tmdbId__c</fullName>
    <label>tmdb ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/tmdbFutureClass.cls
public class tmdbFutureClass
{
    @future (callout=true)
    public static void myFutureMethod(List<integer> listOfId){
        List <tmdbMovieDetailsResponse> results = new List<tmdbMovieDetailsResponse>();
        tmdb tmdbClass = new tmdb();
        List <Movie__c> movieList = new List<Movie__c>();
       
        for(integer id : listOfId){
            tmdbMovieDetailsResponse response = new tmdbMovieDetailsResponse();
            response = tmdbClass.getMovieDetails(id);
            Movie__c currentMovie = new Movie__c();
            currentMovie = [SELECT Description__c, Title__c, Revenue__c, Rating__c, PosterURL__c, Budget__c FROM Movie__c WHERE tmdbId__c=:id];
            currentMovie.Description__c = response.overview;
            currentMovie.Title__c = response.original_title;
            currentMovie.Revenue__c = response.revenue;
            currentMovie.Rating__c = response.vote_average;
            currentMovie.PosterURL__c = response.poster_path;
            currentMovie.Budget__c = response.budget;
            movieList.add(currentMovie);
        }   
        system.debug(movieList);
        if(movieList != null) update movieList;
    }
}