force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdbId__c.field-meta.xml
<CustomField>
    <fullName>tmdbId__c</fullName>
    <label>tmdb ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDB Synchronization Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateMovieBatch.cls
public class UpdateMovieBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public String query;
 
    public Database.QueryLocator start(Database.BatchableContext BC){
        List<Movie__c> listOfMovies = new List<Movie__c>();
        System.debug('BATCH STARTED');
        query = 'SELECT tmdbId__c,TMDBSyncDate__c FROM Movie__c WHERE tmdbId__c != null';
        System.debug(query);
       return Database.getQueryLocator(query);
    }
 
    public void execute(Database.BatchableContext BC, List<Movie__c> scope){
      System.debug('Start execution');
      List<Movie__c> scopeToUpdate = new List<Movie__c>();
       for(Movie__c currentMovie : scope){
         if (currentMovie.TMDBSyncDate__c < System.today().addMonths(-1) || currentMovie.TMDBSyncDate__c == null){
            scopeToUpdate.add(currentMovie);
         }
       }
       tmdb tmdbClass = new tmdb();
       tmdbMovieDetailsResponse response = new tmdbMovieDetailsResponse();
       for(Movie__c currentMovie : scopeToUpdate){
         response = tmdbClass.getMovieDetails(Integer.ValueOf(currentMovie.tmdbId__c));
         currentMovie.Revenue__c = response.revenue;
         currentMovie.Rating__c = response.vote_average;
         currentMovie.TMDBSyncDate__c = System.today();
       }
       
       DataBase.update(scopeToUpdate);
       System.debug('Batch execution finished');
    }
 
    public void finish(Database.BatchableContext BC){
      System.debug('BATCH FINISH');
    }
      
  }